blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/Ionity-Global-Pty-Ltd/FANZi-IO-nity/wiki/Support
    about: Please check the Support wiki page before opening an issue.
